name: MooRTE
author: SamGoody
category: Forms
tags: [wysiwyg, "Rich Text Editor", editor, textarea]
docs: http://siteroller.net/projects/moorte/MoorteDocs.htm
demo: http://siteroller.net/projects/moorte/
current: 0.54
Group: http://groups.google.com/group/moorte